
org.slf4j.simpleLogger.logFile=System.out
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=HH:mm:ss.SSS
org.slf4j.simpleLogger.showLogName=true
org.slf4j.simpleLogger.showShortLogName=true
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.defaultLogLevel=WARN

# Handy Preflux logs, if you don't wanna open its UI (20231117)
org.slf4j.simpleLogger.log.ch.post.it.paisa.preflux.process.repofile.RepofileStatsService=INFO
#org.slf4j.simpleLogger.log.ch.post.it.paisa.preflux.process.taskexecution.TaskStatsService=INFO
#org.slf4j.simpleLogger.log.ch.post.it.paisa.preflux.process.artifactory.ArtifactoryStatsService=INFO
org.slf4j.simpleLogger.log.ch.post.it.paisa.preflux.process.repofile.PrefluxJedis=INFO

# ExpansionHandler 404 houston/gateleen
#org.slf4j.simpleLogger.log.
#org.slf4j.simpleLogger.log.ch.post.it.paisa.houston.process.expansion=TRACE
#org.slf4j.simpleLogger.log.ch.post.it.paisa.houston.process.expansion.ResponseSerializer=TRACE
#org.slf4j.simpleLogger.log.ch.post.it.paisa.houston.process.expansion.ThirdExpansionHandler=TRACE
#org.slf4j.simpleLogger.log.ch.post.it.paisa.houston.process.expansion.json.TreeIteratorService=DEBUG

# General
#org.slf4j.simpleLogger.log.
org.slf4j.simpleLogger.log.ch.post.it.paisa.alice.service.process.core.configuration.EnvironmentEnforcer=ERROR
org.slf4j.simpleLogger.log.ch.post.it.paisa.alice.service.process.core.jmx.JmxPublisher=ERROR
org.slf4j.simpleLogger.log.ch.post.it.paisa.houston.domain.redis.RedisWaiter=DEBUG
org.slf4j.simpleLogger.log.ch.post.it.paisa.houston.process.expansion.DeferredReactorEnqueue=INFO
org.slf4j.simpleLogger.log.ch.post.it.paisa.houston.process.jmx.JmxPublisher=ERROR
org.slf4j.simpleLogger.log.ch.post.it.paisa.preflux.process.fleethelper.control.FleetHelperBuilderService=TRACE
org.slf4j.simpleLogger.log.ch.post.it.paisa.preflux.process.vehiclegroups.VehicleGroupsService=ERROR
org.slf4j.simpleLogger.log.ch.post.it.paisa.preflux.web.controller.OrganizationInformationController=ERROR
org.slf4j.simpleLogger.log.ch.post.it.paisa.preflux.web.httpExceptions=INFO
org.slf4j.simpleLogger.log.io.vertx.core.impl.BlockedThreadChecker=ERROR
org.slf4j.simpleLogger.log.net.schmizz.sshj.transport.TransportImpl.TransportImpl=INFO
org.slf4j.simpleLogger.log.org.swisspush.gateleen.core.configuration.ConfigurationResourceConsumer=ERROR
org.slf4j.simpleLogger.log.org.swisspush.redisques.util.DefaultMemoryUsageProvider=ERROR
